/* 使用 Node.js 22+ 与本机 Chrome/Edge 验证静态页面，无需安装测试依赖。 */
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { pathToFileURL } = require('node:url');
const { spawn } = require('node:child_process');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const browserPath = process.env.PROTOTYPE_BROWSER || [
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'
].find(p => fs.existsSync(p));
if (!browserPath) throw new Error('请通过 PROTOTYPE_BROWSER 指定 Chrome 或 Edge 可执行文件。');
const output = fs.mkdtempSync(path.join(os.tmpdir(), 'teaching-prototype-'));
const profile = path.join(output, 'browser-profile');
const browser = spawn(browserPath, ['--headless=new', '--disable-gpu', '--no-first-run', '--no-default-browser-check', '--remote-debugging-port=0', `--user-data-dir=${profile}`, 'about:blank'], { windowsHide: true, stdio: 'ignore' });
let socket;
let count = 0;
const pending = new Map();
const errors = [];
const network = [];
const check = (value, message) => { assert.ok(value, message); count++; console.log(`PASS ${message}`); };
async function run() {
  browser.on('error', e => errors.push(e.message));
  const portFile = path.join(profile, 'DevToolsActivePort');
  for (let i = 0; i < 100 && !fs.existsSync(portFile); i++) await delay(100);
  assert.ok(fs.existsSync(portFile), `浏览器未启动：${errors.join(', ')}`);
  const port = fs.readFileSync(portFile, 'utf8').split('\n')[0];
  const targets = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  socket = new WebSocket(targets.find(t => t.type === 'page').webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { socket.addEventListener('open', resolve, { once: true }); socket.addEventListener('error', reject, { once: true }); });
  let sequence = 0;
  socket.addEventListener('message', event => {
    const data = JSON.parse(String(event.data));
    if (data.id && pending.has(data.id)) { const p = pending.get(data.id); pending.delete(data.id); clearTimeout(p.timer); if (data.error) p.reject(new Error(JSON.stringify(data.error))); else p.resolve(data.result); }
    if (data.method === 'Runtime.exceptionThrown') errors.push(data.params.exceptionDetails.text + JSON.stringify(data.params.exceptionDetails.exception));
    if (data.method === 'Network.requestWillBeSent' && /^https?:/.test(data.params.request.url)) network.push(data.params.request.url);
  });
  function send(method, params = {}) {
    return new Promise((resolve, reject) => { const id = ++sequence; const timer = setTimeout(() => { pending.delete(id); reject(new Error(`CDP timeout: ${method}`)); }, 10000); pending.set(id, { resolve, reject, timer }); socket.send(JSON.stringify({ id, method, params })); });
  }
  async function evaluate(expression) {
    const r = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true });
    if (r.exceptionDetails) throw new Error(JSON.stringify(r.exceptionDetails));
    return r.result.value;
  }
  const click = selector => evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const change = (selector, value) => evaluate(`{ const el = document.querySelector(${JSON.stringify(selector)}); el.value = ${JSON.stringify(value)}; el.dispatchEvent(new Event('change', {bubbles:true})); }`);
  const fill = (selector, value) => evaluate(`document.querySelector(${JSON.stringify(selector)}).value = ${JSON.stringify(value)}`);
  const submit = selector => evaluate(`document.querySelector(${JSON.stringify(selector)}).requestSubmit()`);
  const text = () => evaluate('document.querySelector("#main")?.innerText || document.body.innerText');
  const go = async page => { await evaluate(`location.hash = ${JSON.stringify(page)}`); await delay(80); };
  const exists = selector => evaluate(`!!document.querySelector(${JSON.stringify(selector)})`);
  const trigger = (action, id = '1', kind = '') => evaluate(`{ const b = document.createElement('button'); b.dataset.action = ${JSON.stringify(action)}; b.dataset.id = ${JSON.stringify(id)}; b.dataset.kind = ${JSON.stringify(kind)}; document.body.appendChild(b); b.click(); b.remove(); }`);
  const forgedSubmit = (kind, values, id = '') => evaluate(`{ const f = document.createElement('form'); f.dataset.form = ${JSON.stringify(kind)}; f.dataset.id = ${JSON.stringify(id)}; for (const [name, value] of Object.entries(${JSON.stringify(values)})) { const input = document.createElement('input'); input.name = name; input.value = value; f.appendChild(input); } document.body.appendChild(f); f.requestSubmit(); f.remove(); }`);
  const validCodes = () => evaluate('window.PrototypeData.projects.every(p => { const t = window.PrototypeData.tasks.find(t => t.id === p.task); const l = window.PrototypeData.labs.find(l => l.id === t.lab); return p.code.startsWith(l.code + "-") && /^[0-9]{3}$/.test(p.code.slice(l.code.length + 1)); }) && new Set(window.PrototypeData.projects.map(p=>p.code)).size === window.PrototypeData.projects.length');
  await send('Runtime.enable');
  await send('Network.enable');
  await send('Page.enable');
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1050, deviceScaleFactor: 1, mobile: false });
  await send('Page.navigate', { url: pathToFileURL(path.join(__dirname, 'index.html')).href });
  for (let i = 0; i < 60 && !(await exists('.stat-card')); i++) await delay(100);
  check(await exists('.stat-card'), 'file:// 直接打开首页');
  check(await evaluate('document.querySelectorAll(".nav-link").length === 10'), '管理员十个功能页面入口');
  check(!await exists('[data-action=new-project]'), '管理员首页无新建项目按钮');
  check(await validCodes(), '初始项目编号遵循实验室编号及三位后缀且唯一');
  await send('Page.captureScreenshot', { format: 'png' }).then(r => fs.writeFileSync(path.join(output, 'overview-desktop.png'), Buffer.from(r.data, 'base64')));
  await click('[data-action=open-week]'); await delay(80);
  check(await exists('.week-grid'), '首页课表快捷入口直接打开周课表');
  for (const page of ['tasks', 'projects', 'terms', 'labs', 'teachers', 'imports', 'reports', 'ai', 'account']) {
    await go(page);
    check(await exists('h1'), `${page} 页面可浏览`);
  }
  await go('tasks');
  await click('[data-action=task-tab-list]');
  await fill('[name=query]', '数据库'); await submit('[data-form=search]');
  check(await evaluate('document.querySelectorAll("tbody tr").length === 1'), '课程搜索筛选');
  await click('[data-action=reset-filter]');
  await click('[data-action=task-tab-week]');
  check(await evaluate('document.querySelectorAll(".lesson").length === 7'), '周课表展示七个教学任务');
  await click('[data-action=next-week]');
  check((await text()).includes('第 3 周'), '周课表切换教学周');
  await click('[data-action=task-detail][data-id="1"]');
  check(await evaluate('document.querySelector("dialog").open && document.querySelectorAll("dialog tbody tr").length === 16'), '课程逐周排课详情');
  await click('dialog [data-action=task-projects]'); await delay(80);
  check(await evaluate('document.querySelectorAll("#main tbody tr").length === 3'), '课程跳转到对应实验项目');
  check(!await exists('[data-action=new-project], [data-action=edit-project], [data-action=delete-project], [data-action=copy-projects], [data-action=project-import]'), '管理员项目页无任何维护入口');
  const beforeAdmin = await evaluate('JSON.stringify(window.PrototypeData)');
  for (const action of ['new-project', 'edit-project', 'copy-projects', 'project-import', 'delete-project']) {
    await trigger(action);
    check(!await evaluate('document.querySelector("dialog").open'), `管理员无法触发 ${action}`);
  }
  await trigger('commit-delete', '1', 'project');
  await forgedSubmit('project', {task: 1, name: '越权新增', school: 'DEMO', discipline: '0809', hours: 4, group: 1});
  await forgedSubmit('project', {task: 1, name: '越权编辑', school: 'DEMO', discipline: '0809', hours: 4, group: 1}, '1');
  await forgedSubmit('copy', {target: 1, source: 8});
  await forgedSubmit('project-import', {task: 1});
  check(await evaluate('JSON.stringify(window.PrototypeData)') === beforeAdmin, '管理员伪造新增编辑删除复制导入操作均不改变演示数据');
  await change('[data-change=role]', 'teacher');
  await change('[data-change=task]', '1');
  await click('[data-action=new-project]');
  check(await evaluate('document.querySelector("[name=code]").readOnly && document.querySelector("[name=code]").value === "36-606-007"'), '新建项目自动显示只读实验室编号');
  await fill('[name=code]', 'INVALID-001');
  await fill('[name=name]', '原型冒烟测试项目'); await submit('[data-form=project]');
  check((await text()).includes('原型冒烟测试项目'), '新增项目更新列表');
  check(await validCodes(), '提交时忽略篡改编号并按规则生成');
  const newId = await evaluate('window.PrototypeData.projects.find(p=>p.name==="原型冒烟测试项目").id');
  await click(`[data-action=edit-project][data-id="${newId}"]`); await fill('[name=name]', '<b>安全文本项目</b>'); await submit('[data-form=project]');
  check((await text()).includes('<b>安全文本项目</b>') && !await exists('#main td b'), '项目编辑与用户输入转义');
  await click(`[data-action=delete-project][data-id="${newId}"]`); await click('[data-action=commit-delete]');
  check(!(await text()).includes('安全文本项目'), '项目删除及确认流程');
  await click('[data-action=copy-projects]'); await submit('[data-form=copy]');
  check((await text()).includes('数据库完整性与事务控制'), '同课程历史项目复制');
  check(await validCodes(), '历史复制使用目标实验室编号并分配唯一后缀');
  await click('[data-action=copy-projects]'); await submit('[data-form=copy]');
  check(await evaluate('document.querySelector("#form-error").textContent.includes("无需重复")'), '防止重复复制历史项目');
  await click('dialog [data-action=close]');
  await click('[data-action=project-import]'); await submit('[data-form=project-import]');
  check((await text()).includes('Excel 导入流程示例项目') && await validCodes(), '教师导入示例项目使用统一编号规则');
  const beforeOtherTeacher = await evaluate('JSON.stringify(window.PrototypeData.projects)');
  await forgedSubmit('project', {task: 1, name: '篡改其他教师项目', school: 'DEMO', discipline: '0809', hours: 4, group: 1}, '4');
  await forgedSubmit('project-import', {task: 2});
  await trigger('commit-delete', '4', 'project');
  check(await evaluate('JSON.stringify(window.PrototypeData.projects)') === beforeOtherTeacher, '教师不能修改删除或导入其他教师项目');
  await change('[data-change=term]', 'history');
  check(!await exists('[data-action=new-project]') && !await exists('[data-action=edit-project]'), '历史学期项目只读');
  await change('[data-change=term]', 'current');
  await change('[data-change=role]', 'teacher');
  check(!await exists('.nav-link[href="#teachers"]') && !await exists('.nav-link[href="#reports"]') && await exists('.nav-link[href="#ai"]'), '教师端包含智能查询且不包含管理入口和统计报表');
  await go('ai'); await click('[data-action=ai-suggestion][data-id="1"]');
  check(await evaluate('document.querySelectorAll(".ai-result tbody tr").length === 3') && !(await text()).includes('李老师'), '教师智能查询只显示本人课程');
  await go('reports');
  check(!await exists('a[href="#reports"]') && !await exists('.bar-chart') && (await text()).includes('我的教学安排'), '教师不可直达报表且首页没有报表快捷入口');
  await send('Page.captureScreenshot', { format: 'png' }).then(r => fs.writeFileSync(path.join(output, 'teacher-desktop.png'), Buffer.from(r.data, 'base64')));
  await go('tasks');
  check(await evaluate('document.querySelectorAll(".lesson").length === 3'), '教师仅看到本人授课任务');
  await go('teachers');
  check((await text()).includes('陈老师，欢迎回来'), '教师直接访问管理路由被拦截');
  await change('[data-change=role]', 'admin');
  await go('teachers');
  check(!await exists('[data-action=edit-teacher], [data-action=new-teacher]') && await exists('[data-action=reset-password]'), '管理员可重置密码但不可编辑教师资料');
  await click('[data-action=reset-password][data-id="1"]');
  check(await evaluate('document.querySelector("dialog").innerText.includes("T2026001")'), '密码重置确认显示目标教师账号');
  await click('dialog [data-action=close]');
  check(!await evaluate('document.querySelector("dialog").open'), '密码重置可以取消');
  await click('[data-action=reset-password][data-id="1"]');
  await click('[data-action=commit-password]');
  check(await evaluate('document.querySelector("dialog").innerText.includes("重置成功（演示）")'), '管理员密码重置演示成功');
  await click('dialog [data-action=close]');
  await change('[data-change=role]', 'teacher');
  await trigger('reset-password'); await trigger('commit-password');
  check(!await evaluate('document.querySelector("dialog").open'), '教师不能发起或确认管理员密码重置');
  await change('[data-change=role]', 'admin');
  await go('tasks');
  check(!await exists('[data-action=new-task]'), '管理员课程只可通过课表导入');
  await go('labs'); await click('[data-action=lab-detail]');
  check(!await exists('[data-action=new-lab], [data-action=edit-lab], [data-action=delete-lab]'), '管理员实验室资料为只读');
  await click('dialog [data-action=close]');
  await go('imports'); await click('[data-action=demo-import]'); await click('[data-action=commit-import]');
  check(await exists('dialog [data-action=confirm-row]'), '导入示例批次与疑点展示');
  await click('dialog [data-action=confirm-row]');
  check(!await exists('dialog [data-action=confirm-row]'), '导入逐行确认');
  await click('dialog [data-action=close]');
  await go('reports');
  await send('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: output });
  await click('[data-action=export-report]');
  for (let i = 0; i < 30 && !fs.existsSync(path.join(output, '实验室教学统计.csv')); i++) await delay(100);
  check(fs.existsSync(path.join(output, '实验室教学统计.csv')), '报表 CSV 导出');
  check(fs.readFileSync(path.join(output, '实验室教学统计.csv'), 'utf8').includes('4992'), 'CSV 使用实际排课人时合计');
  await go('ai'); await click('[data-action=ai-suggestion][data-id="0"]');
  check(await exists('.ai-result table'), '智能查询预设回答与表格');
  await fill('[name=question]', '任意未支持的问题'); await submit('[data-form=ai]');
  check((await text()).includes('仅支持上方三个示例问题'), '智能查询不伪造自定义回答');
  await go('account');
  await fill('[name=old]', 'original-demo'); await fill('[name=password]', 'demo123456'); await fill('[name=confirm]', 'demo123457'); await submit('[data-form=password]');
  check((await text()).includes('两次输入的新密码不一致'), '密码确认校验');
  await fill('[name=confirm]', 'demo123456'); await submit('[data-form=password]');
  check(await evaluate('document.querySelector("[name=password]").value === ""'), '密码演示完成后清空输入');
  await go('overview');
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  for (const page of ['overview', 'tasks', 'projects', 'terms', 'labs', 'teachers', 'imports', 'reports', 'ai', 'account']) {
    await go(page);
    check(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'), `${page} 手机布局无页面横向溢出`);
  }
  await go('overview');
  await evaluate('document.getElementById("toast").classList.remove("show")');
  await send('Page.captureScreenshot', { format: 'png' }).then(r => fs.writeFileSync(path.join(output, 'overview-mobile.png'), Buffer.from(r.data, 'base64')));
  await click('[data-action=toggle-menu]');
  check(await exists('.menu-open'), '手机菜单展开');
  await click('.menu-scrim');
  check(!await exists('.menu-open'), '手机菜单关闭');
  await go('login');
  check(await exists('[data-form=login]'), '登录页展示');
  await submit('[data-form=login]'); await delay(80);
  check(await exists('.stat-card'), '演示登录进入工作台');
  check(errors.length === 0, `浏览器脚本异常数为 0：${errors.join(', ')}`);
  check(network.length === 0, `业务页面无外部 HTTP 请求：${network.join(', ')}`);
  console.log(`\n${count} checks passed. Screenshots and downloads: ${output}`);
}
run().catch(error => { console.error(error); process.exitCode = 1; }).finally(() => { if (socket) socket.close(); for (const p of pending.values()) clearTimeout(p.timer); browser.kill(); });
