<template><div class="teaching-page" v-loading="loading">
<page-heading eyebrow="TEACHING WORKSPACE" :title="(isAdmin?'管理员':$storage.get('adminName'))+'，欢迎回来'" description="把教学安排得井井有条，让每一次实验都有所收获。"><router-link v-if="!isAdmin" class="btn" :to="{path:'/teaching/tasks',query:{termId:$route.query.termId,view:'week'}}"><sf-icon name="calendar"/>查看本周课表</router-link><button class="btn" @click="load">刷新数据</button></page-heading>
<section class="semester-banner"><div><span class="banner-label"><span class="status-dot"></span>{{ selectedTerm ? status(selectedTerm.status) : '全部学期' }}</span><h2>{{ selectedTerm ? selectedTerm.name : '全部学期教学概览' }}</h2><p>从课程计划到实验项目，在这里连接教学的每一步。</p><router-link :to="{path:'/teaching/projects',query:{termId:$route.query.termId}}">进入实验项目 <sf-icon name="arrow"/></router-link></div><div class="banner-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-card art-back"><sf-icon name="book"/><i></i><i></i></div><div class="art-card art-front"><sf-icon name="flask"/><span>LAB</span><div class="art-lines"><i></i><i></i></div></div><span class="art-spark">✦</span><span class="art-dot"></span></div><div class="banner-week"><strong>{{ week || '—' }}</strong><span>{{ week ? '自学期开始的周次' : '请选择学期' }}</span><div class="mini-progress"><i :style="{width:progress+'%'}"></i></div></div></section>
<div class="stat-grid"><div v-for="(card,i) in cards" :key="card[0]" class="stat-card"><div class="stat-top"><span>{{ card[0] }}</span><span class="stat-icon" :class="'tone-'+i"><sf-icon :name="card[3]"/></span></div><div class="stat-value">{{ Number(card[1]).toLocaleString('zh-CN') }}<small>{{ card[2] }}</small></div><div class="stat-foot">{{ card[4] }}</div></div></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-title"><div><h2>{{ isAdmin?'实验室教学分布':'我的教学安排' }}</h2><p>所选学期的实际教学数据</p></div><router-link class="text-link" to="/teaching/reports">查看报表 →</router-link></div><workspace-chart v-if="isAdmin" :rows="reports.labs||[]"/><template v-else><router-link v-for="task in tasks.slice(0,5)" :key="task.id" class="todo" :to="{path:'/teaching/tasks',query:{taskId:task.id}}"><span class="todo-icon blue"><sf-icon name="book"/></span><div><strong>{{ task.course_name }}</strong><p>{{ task.class_composition }} · {{ task.lab_names }}</p></div><sf-icon name="arrow"/></router-link><div v-if="!tasks.length" class="empty">暂无教学安排</div></template></section>
<section class="panel"><div class="panel-title"><h2>待办与提醒</h2><span class="small-dot"></span></div><router-link class="todo" to="/teaching/projects"><span class="todo-icon amber"><sf-icon name="flask"/></span><div><strong>{{ tasks.filter(t=>!Number(t.project_count)).length }} 个教学任务待完善实验项目</strong><p>让教学计划与实验内容保持同步</p></div><sf-icon name="arrow"/></router-link><router-link class="todo" to="/teaching/labs"><span class="todo-icon purple"><sf-icon name="building"/></span><div><strong>{{ lookups.labs.filter(l=>l.equipment_count==null || !l.manager_teacher_id).length }} 间实验室资料待补充</strong><p>完善负责人及设备数量</p></div><sf-icon name="arrow"/></router-link><div class="note-box"><sf-icon name="shield"/>历史项目保留独立版本，可复用至当前学期。</div></section></div>
<section class="panel"><div class="panel-title"><div><h2>所选学期教学任务</h2><p>课程、教师与实验安排，一目了然</p></div><router-link class="text-link" to="/teaching/tasks">全部任务 →</router-link></div><task-table :rows="tasks.slice(0,4)" @detail="openTask"/></section>
</div></template>
<script>
import PageHeading from './teaching/PageHeading'
import WorkspaceChart from '@/components/workspace/Chart'
import TaskTable from '@/components/workspace/TaskTable'
import {shared,request} from './teaching/api'
export default {components:{PageHeading,WorkspaceChart,TaskTable},mixins:[shared],data:()=>({tasks:[],reports:{}}),
computed:{selectedTerm(){return this.lookups.terms.find(t=>String(t.id)===String(this.$route.query.termId))},week(){if(!this.selectedTerm)return 0;const now=Date.now(),start=new Date(this.selectedTerm.starts_on).getTime(),end=new Date(this.selectedTerm.ends_on).getTime();return now<start?0:Math.ceil((Math.min(now,end)-start+1)/604800000)},progress(){if(!this.selectedTerm)return 0;return Math.min(100,Math.max(0,(Date.now()-new Date(this.selectedTerm.starts_on))/(new Date(this.selectedTerm.ends_on)-new Date(this.selectedTerm.starts_on))*100))},cards(){return [['教学任务',this.tasks.length,'个','book',new Set(this.tasks.map(t=>t.course_id)).size+' 门课程 · 所选学期'],['实验项目',this.tasks.reduce((n,t)=>n+Number(t.project_count||0),0),'项','flask','持续完善教学内容'],['使用实验室',(this.reports.labs||[]).length,'间','building','覆盖所选范围的实验场地'],['教学人时',(this.reports.labs||[]).reduce((n,l)=>n+Number(l.person_hours||0),0),'人时','chart','实际排课学时 × 课程选课人数']]}},
watch:{'$route.query.termId':'load'},mounted(){this.load()},methods:{openTask(row){this.$router.push({path:'/teaching/tasks',query:{taskId:row.id}})},async load(){this.loading=true;try{await this.loadLookups();let all=[],page=1,data;do{data=await request('/tasks',{params:{termId:this.$route.query.termId,page,limit:100}});all.push(...data.list);page++}while(data.list.length && all.length<data.total);this.tasks=all;this.reports=await request('/reports',{params:{termId:this.$route.query.termId}})}catch(e){this.fail(e)}finally{this.loading=false}}}}
</script>
